sass:
  sass_dir: _sass

title: DO280 OpenShift Exam Prep
description: Hands-on DO280 OpenShift exam preparation notes

remote_theme: just-the-docs/just-the-docs

url: https://abhilashfunde.github.io
baseurl: /OpenShift

nav_enabled: true
search_enabled: true
heading_anchors: true

color_scheme: light

sass:
  sass_dir: _sass
